### ISSUE TITLE
No error when key is invalid

### ISSUE THREAD

**Issue by victorhurdugaci** [statsig-io/go-sdk#3]
I was trying the Go SDK and by mistake I copied the server secret key without the last character. It took me 10-15 min to figure out why my gate always evaluated to `false` since there's no error to indicate that the key is invalid.

Here's the code to repro:
```go
client := statsig.New("secret-ThisIsNotMySecretKey")
g := client.CheckGate(statsigtypes.StatsigUser{
    UserID: "hello-o1",
}, "victor_gate_1")
fmt.Println(g) // Prints false
```

`statsigtypes` is `statsigtypes "github.com/statsig-io/go-sdk/types"`

**Comment by roim** [comment]
Thanks Victor! We'll get this fixed soon.

**Comment by jkw-statsig** [comment]
Thanks for the feedback! We aren't throwing errors in scenarios like this because we want to make sure we don't crash our users' apps/servers, so we decided to return the default values instead. I agree this is making debugging hard though, so for actionable errors like this, maybe we can print error messages in the console instead?

**Comment by victorhurdugaci** [comment]
I agree, panic would not be the right thing to do. A console message is a reasonable compromise -- that's what the Sentry SDK does.

Cheers and thanks for the very fast responses!
